version: "2.4"

x-logging:
  mainlog: &mainlog
    driver: "fluentd"
    options: 
      tag: "docker.{{.Name}}.{{.ID}}"
      fluentd-address: "localhost:$FLUENTD_PORT"  

services:
    
  postgres:
    container_name: "${CTX_NAME}-run-postgres"
    hostname: "postgres"
    image: "$POSTGRES_IMAGE:$POSTGRES_VERSION"
    extra_hosts:
    - "db:$POSTGRES_HOST_IP"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_POSTGRES
    
  s3_backup:
    container_name: "${CTX_NAME}-run-s3_backup"
    hostname: "s3_backup"
    build: 
      context: .
      dockerfile: "main/awscli/Dockerfile"
      args:
        IMAGE: $AWSCLI_IMAGE
        VERSION: $AWSCLI_VERSION
        PERL_VERSION: $PERL_VERSION
        S3_ACCESS_KEY: $S3_BACKUP_ACCESS_KEY
        S3_SECRET_KEY: $S3_BACKUP_SECRET_KEY
    restart: "unless-stopped"
    volumes: 
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_S3_BACKUP
    