
version: '2.4'

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options: 
      max-size: "50m"

networks:
  log:
    driver: "bridge"

services:
    
  elasticsearch:
    container_name: "${CTX_NAME}-main-elasticsearch"
    hostname: "elasticsearch"
    build: 
      context: .
      dockerfile: "main/elasticsearch/Dockerfile"
      args:
        IMAGE: "$ELASTICSEARCH_IMAGE"
        VERSION: "$ELASTICSEARCH_VERSION"
    restart: "unless-stopped"
    environment:
      cluster.initial_master_nodes: elasticsearch
      ES_JAVA_OPTS: "$ELASTICSEARCH_JAVA_OPTS"
    ports:
    - "$ELASTICSEARCH_PORT:9200"
    networks:
    - "log"
    volumes: 
    - "$DATA_DIR/elasticsearch:/usr/share/elasticsearch/data"
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_ELASTICSEARCH
    
  kibana:
    container_name: "${CTX_NAME}-main-kibana"
    hostname: "kibana"
    build: 
      context: .
      dockerfile: "main/kibana/Dockerfile"
      args:
        IMAGE: "$KIBANA_IMAGE"
        VERSION: "$KIBANA_VERSION"
    restart: "unless-stopped"
    ports:
    - "$KIBANA_PORT:5601"
    networks:
    - "log"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_KIBANA
    