version: "2.4"

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"

networks:
  shared:
    external: true
    name: "${CTX_NAME}-network"

services:

  certbot:
    container_name: "${CTX_PREFIX_RUN}certbot"
    hostname: "certbot"
    build:
      context: ..
      dockerfile: "main/certbot/Dockerfile"
      args:
        IMAGE: $CERTBOT_IMAGE
        VERSION: $CERTBOT_VERSION
    volumes:
    - "$DATA_DIR/sync/certbot/etc/:/etc/letsencrypt/"
    - "$DATA_DIR/sync/certbot/www/:/var/www/certbot/"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_CERTBOT

  mongo_init:
    container_name: "${CTX_PREFIX_RUN}mongo_init"
    hostname: "mongo_init"
    build:
      context: ..
      dockerfile: "main/mongo/Dockerfile"
      args:
        IMAGE: $MONGO_IMAGE
        VERSION: $MONGO_VERSION
    networks:
    - "shared"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_S3_BACKUP

  s3_uploads:
    container_name: "${CTX_PREFIX_RUN}s3_uploads"
    hostname: "s3_uploads"
    build:
      context: ..
      dockerfile: "main/awscli/Dockerfile"
      args:
        IMAGE: $AWSCLI_IMAGE
        VERSION: $AWSCLI_VERSION
        PERL_VERSION: $PERL_VERSION
        S3_ACCESS_KEY: $S3_UPLOADS_ACCESS_KEY
        S3_SECRET_KEY: $S3_UPLOADS_SECRET_KEY
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_S3_UPLOADS

  s3_backup:
    container_name: "${CTX_PREFIX_RUN}s3_backup"
    hostname: "s3_backup"
    build:
      context: ..
      dockerfile: "main/awscli/Dockerfile"
      args:
        IMAGE: $AWSCLI_IMAGE
        VERSION: $AWSCLI_VERSION
        PERL_VERSION: $PERL_VERSION
        S3_ACCESS_KEY: $S3_BACKUP_ACCESS_KEY
        S3_SECRET_KEY: $S3_BACKUP_SECRET_KEY
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_S3_BACKUP
