root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      ctx_full_name:
        non_empty: true
        type: "str"
        description: "context full name / project name (used as a namespace for docker-compose)"
      ctx_prefix_main:
        type: "str"
        required: true
        description: "prefix for the services in the main docker-compose file (permanent services)"
      ctx_prefix_run:
        type: "str"
        required: true
        description: "prefix for the services in the secondary docker-compose file (transient services)"
      type:
        type: "str"
        non_empty: true
        choices: ["app", "web", "db"]
        description: "pod type"
      local:
        type: "bool"
        non_empty: true
        description: "pod in local host"
      data_dir:
        type: "str"
        non_empty: true
        description: "data directory path (when local=true, the path is relative to the pod directory)"
      use_secrets:
        type: "bool"
        non_empty: true
        description: "use secrets instead of environment variables for confidential data"
      use_minio_gateway:
        type: "bool"
        non_empty: true
        description: "specifies that the minio gateway service is being used"
      use_local_s3:
        type: "bool"
        non_empty: true
        description: "specifies that a local s3 service is being used"
      minio_gateway_endpoint:
        type: "str"
        description: "minio gateway endpoint (when use_minio_gateway=true)"
      minio_gateway_access_key:
        type: "str"
        description: "minio gateway access key (when use_minio_gateway=true)"
      minio_gateway_secret_key:
        type: "str"
        description: "minio gateway secret key (when use_minio_gateway=true)"
      local_s3_access_key:
        type: "str"
        description: "local s3 access key (when use_local_s3=true)"
      local_s3_secret_key:
        type: "str"
        description: "local s3 secret key (when use_local_s3=true)"
      db_root_password:
        type: "str"
        description: "database root password"
      db_gui_password:
        type: "str"
        description: "database gui user password"
