root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      pod_type:
        non_empty: true
        type: "str"
        choices: ["app", "web", "db"]
        description: "pod type"
      shared_network:
        type: "str"
        description: "shared network name"
      local:
        non_empty: true
        type: "bool"
        description: "pod in local host"
      main_dir:
        non_empty: true
        type: "str"
        description: "extension pod (this repository) directory"
      main_real_dir:
        non_empty: true
        type: "str"
        description: "extension pod (this repository) directory without links"
      inner_scripts_dir:
        type: "str"
        description: "directory inside containers to have the scripts (for running commands inside containers)"
      use_certbot:
        type: "bool"
        description: "when true, includes a certbot service"
      use_fluentd:
        type: "bool"
        description: "when true, the services logging driver is fluentd"
      fluentd_port:
        type: "str"
        description: "fluentd port in localhost"
      images:
        required: true
        type: "dict"
        description: "services container images"
      memory:
        required: true
        type: "dict"
        description: "services memory limits"
