root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      pod_type:
        non_empty: true
        type: "str"
        choices: ["app", "web", "db"]
        description: "pod type"
      shared_network:
        type: "str"
        description: "shared network name"
      local:
        non_empty: true
        type: "bool"
        description: "pod in local host"
      main_dir:
        non_empty: true
        type: "str"
        description: "extension pod (this repository) directory"
      main_real_dir:
        non_empty: true
        type: "str"
        description: "extension pod (this repository) directory without links"
      inner_scripts_dir:
        type: "str"
        description: "directory inside containers to have the scripts (for running commands inside containers)"
      named_volumes:
        non_empty: true
        type: "bool"
        description: "specify to use named volumes instead of mapping the data in containers to host directories"
      internal:
        non_empty: true
        type: "bool"
        description: "specifies if the pod is internal in the host (no ports mapped to host ports)"
      use_secrets:
        non_empty: true
        type: "bool"
        description: "use secrets instead of environment variables for confidential data"
      use_fluentd:
        non_empty: true
        type: "bool"
        description: "when true, the services logging driver is fluentd"
      use_internal_fluentd:
        non_empty: true
        type: "bool"
        description: "when true, includes a fluentd service"
      use_s3:
        non_empty: true
        type: "bool"
        description: "when true, includes a s3 client service"
      use_local_s3:
        non_empty: true
        type: "bool"
        description: >-
          when true, includes a local s3 server service to be used for
          backups and restores (mainly for development and tests)
      use_nginx:
        non_empty: true
        type: "bool"
        description: "when true, includes a nginx service to act as reverse proxy"
      use_varnish:
        non_empty: true
        type: "bool"
        description: >-
          when true, includes a varnish service to act as a caching layer for the server http responses
      use_pma:
        non_empty: true
        type: "bool"
        description: "when true, includes a phpmyadmin service to be used as a database gui"
      use_adminer:
        non_empty: true
        type: "bool"
        description: "when true, includes an adminer service to be used as a database gui"
      use_theia:
        non_empty: true
        type: "bool"
        description: >-
          when true, includes a theia service to make easy to see the server logs and run
          predefined actions without the need of ssh-ing into the server
      use_minio_gateway:
        non_empty: true
        type: "bool"
        description: "when true, includes a minio gateway service to be used as a gui to access s3 buckets"
      use_custom_ssl:
        non_empty: true
        type: "bool"
        description: >-
          when true, uses custom ssl certificates (instead of certificates generated automatically
          by certbot)
      use_internal_ssl:
        non_empty: true
        type: "bool"
        description: >-
          when true, maps internal ssl certificates to some services so that they can access other,
          internal services, with self-signed certificates
      use_certbot:
        non_empty: true
        type: "bool"
        description: "when true, specifies that certbot is used to generate ssl certificates"
      ghost_environment:
        type: "str"
        choices: ["development", "production"]
        description: "ghost service environment"
      db_host:
        non_empty: true
        type: "str"
        description: "database host (without port)"
      db_port:
        non_empty: true
        type: "str"
        description: "database port"
      db_name:
        non_empty: true
        type: "str"
        description: "database name"
      db_user:
        non_empty: true
        type: "str"
        description: "database user"
      db_gui_user:
        type: "str"
        description: "database gui user"
      fluentd_port:
        non_empty: true
        type: "str"
        description: "fluentd port (in localhost)"
      fluentd_output_plugin:
        non_empty: true
        type: "str"
        choices: ["file", "elasticsearch"]
        description: "fluentd output plugin"
      elasticsearch_host:
        type: "str"
        description: "elasticsearch host (when fluentd_output_plugin=elasticsearch)"
      s3_cli:
        type: "str"
        choices: ["", "awscli", "mc", "rclone"]
        description: "s3 client type"
      ports:
        non_empty: true
        schema: "ports"
        description: "services external ports (in the host)"
      images:
        required: true
        type: "dict"
        description: "services container images"
      memory:
        required: true
        type: "dict"
        description: "services memory limits"
  ports:
    type: "dict"
    props:
      public_http_port:
        non_empty: true
        type: "int"
        description: "public http port; defaults to 80 in a remote host and to 8080 in a local host"
      public_https_port:
        non_empty: true
        type: "int"
        description: "public https port; defaults to 443 in a remote host and to 8443 in a local host"
      private_http_port:
        non_empty: true
        type: "int"
        description: "private http port; defaults to 9080"
      private_https_port:
        non_empty: true
        type: "int"
        description: "private https port; defaults to 9443"
